#!/bin/bash


###############################################################
#             moving to a local installation folder           #
###############################################################

mkdir -p ~/resources/local
cd    ~/resources/local


npm install -g typescript
